import * as vscode from 'vscode';
import { EnterpriseEndpoints, TenantResources } from '../types';
import { TenantConfigurationManager } from './tenantConfigurationManager';
import { TenantDataService } from './tenantDataService';
import { DESIGN_SYSTEM_VERSION, renderDesignSystemDoc } from '../util/designSystem';

/**
 * Generates `.fuuz/AVAILABLE.md` in the workspace: a human- and copilot-readable
 * snapshot of what exists in the active tenant's Fuuz app (module groups,
 * screens, flows, data models, scripts, queries, documents) plus a pointer to
 * the Fuuz MCP server. Dropping this into the repo "defaults" the available
 * surface into the IDE so a developer (and their AI) can orient immediately.
 *
 * Alongside it, writes `.fuuz/DESIGN_SYSTEM.md` — the canonical Fuuz UI design
 * system — so every widget an AI copilot builds through the MCP is themed like
 * core Fuuz by default. AVAILABLE.md points at it.
 */
export class ContextDocWriter {
  constructor(
    private readonly configManager: TenantConfigurationManager,
    private readonly dataService: TenantDataService
  ) {}

  async write(): Promise<vscode.Uri | null> {
    const folder = vscode.workspace.workspaceFolders?.[0];
    if (!folder) {
      void vscode.window.showWarningMessage('Open a folder to generate the Fuuz context file.');
      return null;
    }

    const enterprise = this.configManager.getActiveEnterprise();
    const tenant = this.configManager.getActiveTenant();
    if (!enterprise || !tenant) {
      void vscode.window.showWarningMessage('Select an active Fuuz tenant first.');
      return null;
    }

    const resources = await this.dataService.getTenantResources(tenant);
    const disabled = new Set(this.configManager.disabledTools(enterprise.id, tenant.id));
    const dir = vscode.Uri.joinPath(folder.uri, '.fuuz');
    await vscode.workspace.fs.createDirectory(dir);

    // Canonical design system — refreshed on every generate so it tracks the
    // extension version. AVAILABLE.md references it (see render()).
    const designUri = vscode.Uri.joinPath(dir, 'DESIGN_SYSTEM.md');
    await vscode.workspace.fs.writeFile(designUri, Buffer.from(renderDesignSystemDoc(), 'utf8'));

    const uri = vscode.Uri.joinPath(dir, 'AVAILABLE.md');
    const md = this.render(enterprise.name, tenant.name, this.configManager.endpointsFor(enterprise, tenant), resources, disabled);
    await vscode.workspace.fs.writeFile(uri, Buffer.from(md, 'utf8'));
    return uri;
  }

  private render(
    enterpriseName: string,
    tenantName: string,
    endpoints: EnterpriseEndpoints,
    r: TenantResources | null,
    disabledTools: Set<string>
  ): string {
    const lines: string[] = [];
    lines.push(`# Fuuz app surface — ${enterpriseName} › ${tenantName}`);
    lines.push('');
    lines.push('> Generated by the Fuuz VS Code extension. This is a snapshot to help you');
    lines.push('> and your AI copilot understand what exists in this tenant. For anything');
    lines.push('> involving a **flow, screen, script, schema, data model, or document**,');
    lines.push('> work through the **Fuuz MCP server** in VS Code rather than editing by hand.');
    lines.push('');
    lines.push('## UI / design system');
    lines.push(`When building any **HTML/SVG widget output** (a script that returns a \`data:text/html\` URL or a chart dataSource), apply the canonical Fuuz design system in [\`DESIGN_SYSTEM.md\`](./DESIGN_SYSTEM.md) (v${DESIGN_SYSTEM_VERSION}) **by default** — DM Sans, neutral-charcoal/white surfaces, violet \`#5B30DF\` accent, the shared status palette. Deviate only when the user asks for something unique.`);
    lines.push('');
    lines.push('## Endpoints');
    lines.push(`- **MCP server:** \`${endpoints.mcp}\``);
    lines.push(`- **Flow execution:** \`${endpoints.flowExecution}\``);
    lines.push(`- **Webhook:** \`${endpoints.webhook}{topic}\``);
    lines.push('');
    lines.push('> GraphQL queries/mutations are saved operations — execute one by building a');
    lines.push('> data flow that references it and running that flow through the flow execution endpoint.');
    if (r?.lastSyncedAt) lines.push(`- **Last synced:** ${r.lastSyncedAt}`);
    lines.push('');

    const mcp = r?.mcp;
    if (!mcp) {
      lines.push('_No MCP resources synced yet. Run **Fuuz: Sync Tenant Data**._');
      lines.push('');
      return lines.join('\n');
    }
    const names = (items: any[] | undefined) => (items ?? []).map(i => i.name).join(', ');

    // Agent tools — enabled only (disabled ones are intentionally withheld).
    const tools = (mcp.tools ?? []).filter(t => !disabledTools.has(t.name));
    lines.push('## Agent tools (enabled)');
    if (tools.length === 0) lines.push('_None enabled._');
    for (const t of tools) {
      lines.push(`- \`${t.name}\`${t.kind === 'dataflow' ? ' _(custom data flow)_' : ''}${t.description ? ` — ${String(t.description).split('\n')[0]}` : ''}`);
    }
    if (disabledTools.size) lines.push(`\n_${disabledTools.size} tool(s) disabled for agents and omitted._`);
    lines.push('');

    lines.push('## Application');
    if (!mcp.application?.length) lines.push('_None._');
    for (const mg of mcp.application ?? []) {
      lines.push('');
      lines.push(`### ${mg.name}`);
      for (const m of mg.modules ?? []) {
        lines.push(`- **module** \`${m.name}\``);
        if (m.screens?.length) lines.push(`  - screens: ${names(m.screens)}`);
        if (m.flows?.length) lines.push(`  - flows: ${names(m.flows)}`);
        if (m.dataModels?.length) lines.push(`  - data models: ${names(m.dataModels)}`);
      }
    }
    lines.push('');

    if (mcp.systemDataModels?.length) {
      lines.push('## System data models');
      lines.push(names(mcp.systemDataModels));
      lines.push('');
    }

    return lines.join('\n');
  }
}
